### ISSUE TITLE
Method: Projectile hit wall

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/LetsCreateGame#11]
The update method should check if a arrow hit a wall. If so, the abstract method "hitWall()" should get triggered. Add this method. The Classes that extend (Projectile) implement their own reactions to the hitting of the wall.

**Comment by LuposX** [comment]
#26 needs to be done first.

**Comment by LuposX** [comment]
Information for bouncing off:
https://stackoverflow.com/questions/55793641/2d-perfect-projectile-reflection-with-rotation

Physik unterricht "Einschlagswinkel" == "Auschlagswinkel"

**Comment by GloeStoe** [comment]
Eingeführt. Die Methode wallHitSpecialReaction() ersetzt hitWall().
