### ISSUE TITLE
Trigger onCollision() in Class "Entity"

### ISSUE THREAD

**Issue by GloeStoe** [LuposX/LetsCreateGame#21]
Programmiere eine Klasse, die diese Methode bei einer Kollision zweier Entities aufruft. Achte darauf, dass die Methoden pro Klasse nur einmal ausgeführt werden.

**Comment by LuposX** [comment]
Aber solllen nicht unterschiedliche dinge passieren von entity zu entity? Bei dem vorschlag würde ja egal welches entity welches berührt das gleiche passieren oder nicht?
Oder meinst du damit eine methode in entity die überall implementiert werden muss?
