### ISSUE TITLE
Implement hitboxes

### ISSUE THREAD

**Issue by LuposX** [LuposX/LetsCreateGame#26]
Implement hitboxes for entities like player and hostile mobs.

**Comment by GloeStoe** [comment]
Der Parameter shape in jedem Entity ist als "Hitbox" gedacht. Die Kollision mit der Testmap muss wahrscheinlich anders impementiert werden

**Comment by GloeStoe** [comment]
Vorschlag: Die Kollision zwischen zwei Entitys wird von der Klasse "Controls" überprüft und dann werden die Methoden in den Objekten aufgerufen . Siehe #21
Die Kollision mit der Wand wird jedoch von jedem Objekt bei Bedarf selbst überprüft. z.B. beim Bewegen des Spielers

**Comment by LuposX** [comment]
Ich entferne das mit der map. Das ist nen duplicate issue.

**Comment by LuposX** [comment]
> Der Parameter shape in jedem Entity ist als "Hitbox" gedacht. Die Kollision mit der Testmap muss wahrscheinlich anders impementiert werden
