### ISSUE TITLE
Schüsse bleiben stecken in der wand

### ISSUE THREAD

**Issue by LuposX** [LuposX/LetsCreateGame#36]
Schüsse bleiben in der wand stecken wenn man auf Verbindung-tiles schießt
und wenn `wallHitSpeedLoss` hoch ist e.g. `0.7f`
![image](https://user-images.githubusercontent.com/36456825/78694818-844e3b80-78fd-11ea-8801-658bb6011241.png)

**Comment by GloeStoe** [comment]
Kann ich nicht reproduzieren. Bei  mir passier das nicht

**Comment by LuposX** [comment]
@GloeStoe probiers nochmal mit wallHitSpeedLoss = 0.8f;

**Comment by LuposX** [comment]
Immer noch da:
![image](https://user-images.githubusercontent.com/36456825/78818869-9f8c7a00-79d5-11ea-9a1a-e28cb3f725c2.png)

**Comment by GloeStoe** [comment]
Das zweite Bild liegt daran, dass kein Cooldown drin ist und sich die Schüsse gegenseitig zerstören. Das erste Bild sollte jetzt gefixt sein
